### ISSUE TITLE
Related your blog

### ISSUE THREAD

**Issue by ashishgarg624** [maximusk/angular-seed#2]
Hi,

I read your blog (https://blog.angularindepth.com/how-to-manually-bootstrap-an-angular-application-9a36ccf86429) in which you explain project in a good manner but when i create project and run npm start it gave error of (does not found dist/main.js) because location of main.js file is dist/src/main.js. Can you please help me how can i change path of main.js from dist/src/main.js to dist/main.js.

Thanks.

**Comment by maximusk** [comment]
Did you simply clone this project?

**Comment by ashishgarg624** [comment]
No, i got reference from attached blog and create new project and face this issue.

**Comment by maximusk** [comment]
maybe use the sample project from this github repo

**Comment by ashishgarg624** [comment]
ok thank you.
